server:
  port: ${random.int[10000,19999]}


#spring:
#  quartz:
#  properties:
#    org:
#      quartz:
#        scheduler:
#          instanceName: ClusterQuartz_Demo
#          instanceId: AUTO
#          wrapJobExecutionInUserTransaction: false
#        jobStore:
#          isClustered: true
#          class: org.quartz.impl.jdbcjobstore.JobStoreTX
#          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#          useProperties: true
#          tablePrefix: QRTZ_
#          dataSource: quartz_db
#        threadPool:
#          class: org.quartz.simpl.SimpleThreadPool
#          threadCount: 10
#          threadPriority: 5
#          makeThreadsDaemons: true
#          threadsInheritContextClassLoaderOfInitializingThread: true
#        dataSource:
#          quartz_db:
#            driver: com.mysql.cj.jdbc.Driver
#            URL: jdbc:mysql://127.0.0.1:3306/quartz_db?useUnicode=true&characterEncoding=UTF-8
#            user: root
#            password: 123456

#  jdbc-store-type: jdbc
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    name: quartz_db

